### ISSUE TITLE
Angular v16 is not supported

### ISSUE THREAD

**Issue by djonmayer** [bluehalo/ngx-leaflet-markercluster#85]
I cannot use this extension with Angular v15. When I try to install it I get this error message:

λ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: webbpl@1.5.0
npm ERR! Found: @angular/common@16.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^16.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"15" from @asymmetrik/ngx-leaflet-markercluster@15.0.0
npm ERR! node_modules/@asymmetrik/ngx-leaflet-markercluster
npm ERR!   @asymmetrik/ngx-leaflet-markercluster@"^15.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See d:\tools\nodejs\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     d:\tools\nodejs\npm-cache\_logs\2023-05-17T08_02_01_399Z-debug-0.log`

**Comment by m8xp0w3r** [comment]
use `npm i -f ` for installation.

**Comment by reblace** [comment]
Just published a version explicitly compatible with ng16
